dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run python manage.py test

notifications:
  email: false

env:
  - BLIZZARD_CLIENT_ID=123456789 BLIZZARD_CLIENT_SECRET=987654321
