dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.8"

install:
  - pip install poetry
  - poetry install

script:
  - poetry run task test

notifications:
  email: false

env:
  - BLIZZARD_CLIENT_ID=123456789 BLIZZARD_CLIENT_SECRET=987654321 REDIS_URL=192837465
