# Generated by Django 2.2.2 on 2019-06-06 05:33

import django.db.models.manager
import enumfields.fields
from django.db import migrations, models

import app.models.player


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("realm", models.CharField(max_length=10)),
                ("region", models.CharField(max_length=10)),
                (
                    "rank",
                    enumfields.fields.EnumIntegerField(enum=app.models.player.Rank),
                ),
                ("username", models.CharField(max_length=30)),
                ("bnet_id", models.CharField(max_length=30)),
                ("race", models.CharField(max_length=7)),
                ("mmr", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("clan", models.CharField(max_length=10, null=True)),
                ("profile_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            managers=[("players", django.db.models.manager.Manager()),],
        ),
    ]
