# Generated by Django 2.2.2 on 2019-06-18 06:34

import app.models.player
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190617_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='region',
            field=enumfields.fields.EnumField(enum=app.models.player.Region, max_length=2),
        ),
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', enumfields.fields.EnumIntegerField(enum=app.models.player.Rank)),
                ('username', models.CharField(max_length=30)),
                ('bnet_id', models.CharField(max_length=30)),
                ('mmr', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('clan', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
            managers=[
                ('player_snapshots', django.db.models.manager.Manager()),
            ],
        ),
    ]
