# Generated by Django 2.2.2 on 2019-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190618_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bnet_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='clan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
