# Generated by Django 3.0.2 on 2020-03-18 06:38

import app.models.player
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190708_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ladder_id', models.CharField(max_length=12)),
                ('profile_id', models.CharField(max_length=12)),
                ('realm', models.IntegerField()),
                ('region', models.IntegerField()),
                ('rank', enumfields.fields.EnumIntegerField(default=2, enum=app.models.player.Rank)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
