# Generated by Django 3.0.4 on 2020-03-22 18:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_player_game_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="mmr_history",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(name="PlayerSnapshot",),
    ]
