# Generated by Django 3.0.4 on 2020-03-22 18:57

from django.db import migrations

from app.models.fields import JSONField


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_player_game_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="mmr_history", field=JSONField(default=dict),
        ),
        migrations.DeleteModel(name="PlayerSnapshot",),
    ]
